package com.gondroid.core.presentation.designsystem

import androidx.compose.ui.graphics.Color

// Light — Deep Indigo primary + Amber/Gold tertiary
val primaryLight = Color(0xFF3949AB)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDCE1FF)
val onPrimaryContainerLight = Color(0xFF00105C)
val secondaryLight = Color(0xFF5B5D72)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDFE1F9)
val onSecondaryContainerLight = Color(0xFF181A2C)
val tertiaryLight = Color(0xFF785900)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDF9E)
val onTertiaryContainerLight = Color(0xFF261A00)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFBF8FF)
val onBackgroundLight = Color(0xFF1B1B21)
val surfaceLight = Color(0xFFFBF8FF)
val onSurfaceLight = Color(0xFF1B1B21)
val surfaceVariantLight = Color(0xFFE3E1EC)
val onSurfaceVariantLight = Color(0xFF46464F)
val outlineLight = Color(0xFF767680)
val outlineVariantLight = Color(0xFFC7C5D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303036)
val inverseOnSurfaceLight = Color(0xFFF2EFF7)
val inversePrimaryLight = Color(0xFFB6C4FF)
val surfaceDimLight = Color(0xFFDCD9E1)
val surfaceBrightLight = Color(0xFFFBF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF5F2FA)
val surfaceContainerLight = Color(0xFFF0EDF5)
val surfaceContainerHighLight = Color(0xFFEAE7EF)
val surfaceContainerHighestLight = Color(0xFFE4E1E9)

// Dark — Indigo + Amber
val primaryDark = Color(0xFFB6C4FF)
val onPrimaryDark = Color(0xFF08218A)
val primaryContainerDark = Color(0xFF263EA1)
val onPrimaryContainerDark = Color(0xFFDCE1FF)
val secondaryDark = Color(0xFFC3C5DD)
val onSecondaryDark = Color(0xFF2C2F42)
val secondaryContainerDark = Color(0xFF434659)
val onSecondaryContainerDark = Color(0xFFDFE1F9)
val tertiaryDark = Color(0xFFF5BF48)
val onTertiaryDark = Color(0xFF402D00)
val tertiaryContainerDark = Color(0xFF5C4200)
val onTertiaryContainerDark = Color(0xFFFFDF9E)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF131318)
val onBackgroundDark = Color(0xFFE4E1E9)
val surfaceDark = Color(0xFF131318)
val onSurfaceDark = Color(0xFFE4E1E9)
val surfaceVariantDark = Color(0xFF46464F)
val onSurfaceVariantDark = Color(0xFFC7C5D0)
val outlineDark = Color(0xFF91909A)
val outlineVariantDark = Color(0xFF46464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE4E1E9)
val inverseOnSurfaceDark = Color(0xFF303036)
val inversePrimaryDark = Color(0xFF3949AB)
val surfaceDimDark = Color(0xFF131318)
val surfaceBrightDark = Color(0xFF39393F)
val surfaceContainerLowestDark = Color(0xFF0E0E13)
val surfaceContainerLowDark = Color(0xFF1B1B21)
val surfaceContainerDark = Color(0xFF1F1F25)
val surfaceContainerHighDark = Color(0xFF2A292F)
val surfaceContainerHighestDark = Color(0xFF35343A)
